a = type(1)
b = type(1.50)
c = type(True)
d = type("One")
print("The number 1 is a.. " + str(a) + " ..Int, is short for Integer.")
print("The number 1.5 is a.. " + str(b) + " ..Float is a number with a decimal point.")
print("The phrase 'True' is a.. " + str(c) + " ..Bool, is short for Boolean.")
print("The word 'One' is a.. " + str(d) + " ..Str, is short for String.")